### ISSUE TITLE
Bugs on MLE analysis

### ISSUE THREAD

**Issue by AndreaBulgarelli** [AGILESCIENCE/Agilepy#11]
Hi @LeoBaro there are some bugs on MLE analysis. All are listed here (search "BUG" keyword)

https://github.com/ASTRO-EDU/GRB221009A/blob/main/GRB221009A-MLE-AB1-Copy1.ipynb

**Comment by LeoBaro** [comment]
- It seems that start time is truncated in `lightCurveMLE` 
- Check if EMIN and EMAX parameters in "selection" section are actually used.
- displayLightCurve raises an exception if the map generation considered multiple energy bins
- If filter code is equal to 5, log a warning

**Comment by AndreaBulgarelli** [comment]
Hi @LeoBaro the point
"Check if EMIN and EMAX parameters in "selection" section are actually used. They are not updated from the energybins list."
is fixed.

You can proceed with other points

**Comment by AndreaBulgarelli** [comment]
Filtercode values

filtercode = 0 ALL --> T
filtercode = 1 <> L --> GS
filtercode = 2 <> G --> LS
filtercode = 3 <> G <> L --> S (+P) 
filtercode = 4 <> S --> GL
filtercode = 5 <> S <> L = G (+P)
filtercode = 6 <> S <> G = L (+P)
filtercode = 7 <> S <> G <> L = null --> P (+P)
