### ISSUE TITLE
Update instructions for development

### ISSUE THREAD

**Issue by gabriele-panebianco-inaf** [AGILESCIENCE/Agilepy#17]
The [Development](https://agilepy.readthedocs.io/en/1.6.3/help/development.html) page of Documentation mention the possibility to develop in conda environment. Alessandro ursi tried but failed due to lack of environment.yml.

Also the Docker section mentions conda inside Docker, wasn't it removed in v1.6.0?

1. We need to update the Documentation page with one clear set of instructions.
2. @LeoBaro When we need to update a package version and test the existing code in a new environment what should we change?

@AndreaBulgarelli

**Comment by gabriele-panebianco-inaf** [comment]
I used the following instructions with  `agilescience/agilepy-recipe:BUILD25b3626`, but @AndreaBulgarelli mentioned had issues, maybe we should use `agilescience/agilepy-recipe:latest` or `agilescience/agilepy:release-<version>`?


---------
**Instructions**
1. Prepare Workspace: create `agile` directory where you need, and `agile/shared_dir` inside it. Then clone repository in `agile`. 
    ```
    agile$ mkdir shared_dir
    agile$ git clone git@github.com:AGILESCIENCE/Agilepy.git
    ```
2. Pull Docker image
    ```
    agile$ docker pull agilescience/agilepy-recipe:BUILD25b3626
    ```
3. Build Container from Docker Image.
    ```
    docker run --rm -t -d -p 8888:8888 --name agilepy_dev \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v /home/gabriele/Documents/agile/Agilepy:/Agilepy \
    -v /home/gabriele/Documents/agile/shared_dir:/shared_dir \
    agilescience/agilepy-recipe:BUILD25b3626
    ```
4. Run Container:
    ```
    agile/Agilepy$ docker exec -it agilepy_dev bash -l
    ```
5. Activate environment, switch to working branch (e.g `develop`) and install editable software
    ```
    $ source /opt/venv/agilepy/bin/activate
    $ cd /Agilepy
    $ git checkout develop
    $ pip install -e .
    ```
8. Launch notebook if required, on browser search `http://localhost:8888/tree`
    ```
    $ jupyter notebook --ip="*" --port=8888 --no-browser --notebook-dir="/shared_dir" --NotebookApp.token="AGILEnotebook#" &
    ```

9. Stop container with `exit` and
    ```
    $ docker stop agilepy_dev
    ```

**Comment by LeoBaro** [comment]
Thanks a lot, @gabriele-panebianco-inaf. 
Some comments:
- the `agile/shared_dir` directory is not mandatory. Potentially you can mount the `agile` directory only (that contains the Agilepy cloned repository), with `-v /home/gabriele/Documents/agile/Agilepy:/agile`
- The `--notebook-dir` option should point to `Agilepy/agilepy/notebooks` 
- We should change the port mapping `-p 8888:8888`. 8888 is a standard used port. Using 8888 inside the container is fine because we don't have any other service. But it's better to map it on the host on a different port, such as 8090.

**Comment by gabriele-panebianco-inaf** [comment]
Hi @LeoBaro, thank you!

> Potentially you can mount the agile directory only (that contains the Agilepy cloned repository), with` -v /home/gabriele/Documents/agile:/agile`

> But it's better to map it on the host on a different port, such as 8090 (so -p 8090:8888)

That's smarter!

> Do you know how to update the documentation? Have you already started to work on it? Otherwise we should open a branch and a merge request.

I opened a new branch from `master`, now I just need to edit [Agilepy/docs/source/help/development.rst](https://github.com/AGILESCIENCE/Agilepy/blob/17-update-instructions-for-development/docs/source/help/development.rst), right?

**Comment by LeoBaro** [comment]
Yes, right, then open a merge request from <your branch> => <dev> an mention this issue please.

**Comment by gabriele-panebianco-inaf** [comment]
@LeoBaro shouldn't we use "your branch" => "master" in order to actually change the [webpage](https://agilepy.readthedocs.io/en/1.6.3/help/development.html)?

**Comment by LeoBaro** [comment]
There's a button in the bottom left of the documentation webpage to change the version (branches and tags). But you're right, in this case, let's update the master branch.

**Comment by gabriele-panebianco-inaf** [comment]
cool, thanks!
