### ISSUE TITLE
Add flux correction to the method ag.loadSourcesFromCatalog

### ISSUE THREAD

**Issue by AndreaBulgarelli** [AGILESCIENCE/Agilepy#21]
Add flux correction to the method ag.loadSourcesFromCatalog("2AGL", rangeDist = (0, 10))

otherwise the multi-source analysis can be done only in the energy range 100-10000 Mev

**Comment by AndreaBulgarelli** [comment]
`#if different from default energy range of input source list, generate a new sourcelist with the energy range of the input maps
if(emin_sin.to_f != p.emin_sources.to_f or emax_sin.to_f != p.emax_sources.to_f)
        puts "change the flux"
        listsourceold = listsource
        listsource = format("en_%05d_%05d_", emin_sin, emax_sin) + listsource
        fouts = File.new(listsource, "w")
        File.open(listsourceold).each_line do | line |
        l = line.split(" ")
        gamma = l[3].to_f
        fl = l[0].to_f

                c = p.emin_sources.to_f
                d = p.emax_sources.to_f
                a = emin_sin.to_f
                b = emax_sin.to_f

        p1 = fl * (gamma-1) / ( c ** (1-gamma) - d ** (1-gamma) )

        f1 = (p1 / (gamma-1)) * ( a ** (1-gamma) - b ** (1-gamma) )

        fouts.write(f1.to_s)
        for ii in 1..l.size()
                fouts.write(" " + l[ii].to_s)
        end
        fouts.write("\n")
        end
        fouts.close()
end
`

**Comment by LeoBaro** [comment]
- emin_sources and emax_sources can be eliminated
